#! /bin/bash

convertYamlToJson() {
    python3 -c 'import sys, yaml, json; json.dump(yaml.safe_load(sys.stdin), sys.stdout, indent=4)' < $1 > "${1%".yaml"}.json"
}

export -f convertYamlToJson;

find api -type f -name "*.json" -delete;
find api -type f -name "*.yaml" -exec bash -c 'convertYamlToJson "$0"' {} \;
