#! /bin/bash

# Generate the timestamp version file content
date +%s > api/v1/timestamp_version.yaml

./generate_api_files_all_yaml
./generate_api_json_files
find . -name ".DS_Store" -delete
./validate_api_files
